version: '3'
services:
  duckling:
    image: rasa/duckling
    ports:
     - "8000:8000"
    command: stack exec duckling-example-exe 
  rasa_en:
    image: rasa_core_latest
    build:
      context: .
    volumes:
      - ./data:/app/data
    ports:
      - "5005:5005"
    command: python -m rasa_core.run   --enable_api -c rest  -d /app/data/sumIT-demo-bot/models/core/dialogue -u data/sumIT-demo-bot/models/nlu/nlu_model --endpoints endpoints.yml --credentials credentials.yml --debug
  action:  
    image: action_server
    build:
      context: ./actions
    volumes: 
     - ./actions:/app
    ports:
      - "5055:5055"
    command : python -m rasa_core_sdk.endpoint --actions actions 
  nlg:  
    image: nlg_server
    build:
      context: ./nlg
    volumes:
      - ./data:/app/data
    ports:
      - "5056:5056"
    command : python nlg/nlg_server.py --port 5056 --domain data/sumIT-demo-bot/domain.yml
